package it.uniroma2.sdcc.trafficcontrol.boltsFirstQuery;

import it.uniroma2.sdcc.trafficcontrol.bolts.AbstractRankerBolt;
import it.uniroma2.sdcc.trafficcontrol.entity.ranking.Rankings;
import org.apache.storm.tuple.Tuple;

import java.util.logging.Logger;

import static it.uniroma2.sdcc.trafficcontrol.constants.StormParams.RANKABLE_OBJECT;

/**
 * This bolt merges incoming {@link Rankings}.
 * <p/>
 * It can be used to merge intermediate rankings generated by {@link PartialRankingsBolt} into a final,
 * consolidated ranking. To do so, configure this bolt with a globalGrouping on {@link PartialRankingsBolt}.
 */
public class GlobalRankingsBolt extends AbstractRankerBolt {

    private final static String CLASS_NAME = GlobalRankingsBolt.class.getSimpleName();
    private final static Logger LOGGER = Logger.getLogger(CLASS_NAME);

    public GlobalRankingsBolt() {
        super();
    }

    public GlobalRankingsBolt(int topN) {
        super(topN);
    }

    public GlobalRankingsBolt(int topN, int emitFrequencyInSeconds) {
        super(topN, emitFrequencyInSeconds);
    }

    @Override
    public void updateRankingsWithTuple(Tuple tuple) {
        Rankings rankingsToBeMerged = (Rankings) tuple.getValueByField(RANKABLE_OBJECT);
        super.getRankings().updateWith(rankingsToBeMerged);
        super.getRankings().pruneZeroCounts();
    }

    @Override
    public void printR() {
        System.out.println(getRankings().toString());
    }

    @Override
    public Logger getLogger() {
        return LOGGER;
    }

}
